// Auto-generated by platform/android/scripts/regen_stubs.sh.
//
// Bionic's dlopen() rejects .so files with GLOBAL UND symbols not provided
// by an already-loaded shared library. We link with
// -Wl,--unresolved-symbols=ignore-all so the link succeeds despite leftover
// desktop-only references (SDL2, NFD, RecompFrontend recompui/recompinput,
// re-spirv, ImGui_SDL2). To make dlopen happy we provide a tiny per-symbol
// stub for every UND name that logs the offending symbol via logcat and
// aborts. The boot path in src/main/android_run_game.cpp deliberately
// avoids invoking these code paths; if one of them does fire, the logcat
// line tells us exactly which to implement next.
//
// EXCLUDES (don't stub these - system libraries provide them):
//   - Android NDK funcs matching ^A[A-Z][a-zA-Z]*_  (libandroid.so)
//   - __android_log_*  (liblog.so)
//   - vk*, volk*       (libvulkan.so + volk)
//   - pthread_*, sem_* (Bionic libc)
//   - libm / libdl     (Bionic)
//   - libc++_shared.so symbols (_ZNSt*, _ZNKSt*, _ZN6__ndk1*, etc.)
//   - libc++abi __cxa_*, _Unwind_*, __gxx_personality_*
//
// Regenerate after the link-error list changes:
//   platform/android/scripts/regen_stubs.sh

#ifdef __ANDROID__
#include <android/log.h>
#include <stdlib.h>

extern "C" __attribute__((noreturn)) void android_unimplemented_stub_named(const char* name) {
    __android_log_print(ANDROID_LOG_FATAL, "BK64-Stub",
        "unimplemented Android stub called: %s -- aborting", name);
    abort();
}

extern "C" void SDL_BuildAudioCVT() { android_unimplemented_stub_named("SDL_BuildAudioCVT"); }
extern "C" void SDL_ConvertAudio() { android_unimplemented_stub_named("SDL_ConvertAudio"); }
extern "C" void SDL_CreateWindow() { android_unimplemented_stub_named("SDL_CreateWindow"); }
extern "C" void SDL_GL_GetDrawableSize() { android_unimplemented_stub_named("SDL_GL_GetDrawableSize"); }
extern "C" void SDL_GameControllerAddMappingsFromRW() { android_unimplemented_stub_named("SDL_GameControllerAddMappingsFromRW"); }
extern "C" void SDL_GetCurrentVideoDriver() { android_unimplemented_stub_named("SDL_GetCurrentVideoDriver"); }
extern "C" void SDL_GetError() { android_unimplemented_stub_named("SDL_GetError"); }
extern "C" void SDL_GetEventFilter() { android_unimplemented_stub_named("SDL_GetEventFilter"); }
extern "C" void SDL_GetGlobalMouseState() { android_unimplemented_stub_named("SDL_GetGlobalMouseState"); }
extern "C" void SDL_GetKeyboardFocus() { android_unimplemented_stub_named("SDL_GetKeyboardFocus"); }
extern "C" void SDL_GetMouseFocus() { android_unimplemented_stub_named("SDL_GetMouseFocus"); }
extern "C" void SDL_GetQueuedAudioSize() { android_unimplemented_stub_named("SDL_GetQueuedAudioSize"); }
extern "C" void SDL_GetRendererOutputSize() { android_unimplemented_stub_named("SDL_GetRendererOutputSize"); }
extern "C" void SDL_GetWindowFlags() { android_unimplemented_stub_named("SDL_GetWindowFlags"); }
extern "C" void SDL_GetWindowFromID() { android_unimplemented_stub_named("SDL_GetWindowFromID"); }
extern "C" void SDL_GetWindowPosition() { android_unimplemented_stub_named("SDL_GetWindowPosition"); }
extern "C" void SDL_GetWindowSize() { android_unimplemented_stub_named("SDL_GetWindowSize"); }
extern "C" void SDL_GetWindowWMInfo() { android_unimplemented_stub_named("SDL_GetWindowWMInfo"); }
extern "C" void SDL_Init() { android_unimplemented_stub_named("SDL_Init"); }
extern "C" void SDL_InitSubSystem() { android_unimplemented_stub_named("SDL_InitSubSystem"); }
extern "C" void SDL_OpenAudioDevice() { android_unimplemented_stub_named("SDL_OpenAudioDevice"); }
extern "C" void SDL_PauseAudioDevice() { android_unimplemented_stub_named("SDL_PauseAudioDevice"); }
extern "C" void SDL_QueueAudio() { android_unimplemented_stub_named("SDL_QueueAudio"); }
extern "C" void SDL_RWFromFile() { android_unimplemented_stub_named("SDL_RWFromFile"); }
extern "C" void SDL_SetEventFilter() { android_unimplemented_stub_named("SDL_SetEventFilter"); }
extern "C" void SDL_SetTextInputRect() { android_unimplemented_stub_named("SDL_SetTextInputRect"); }
extern "C" void SDL_StartTextInput() { android_unimplemented_stub_named("SDL_StartTextInput"); }
extern "C" void SDL_StopTextInput() { android_unimplemented_stub_named("SDL_StopTextInput"); }
extern "C" void SDL_WarpMouseInWindow() { android_unimplemented_stub_named("SDL_WarpMouseInWindow"); }
extern "C" void SDL_WasInit() { android_unimplemented_stub_named("SDL_WasInit"); }
// rand / system / ungetc come from Bionic libc — they were missing from
// regen_stubs.sh's LIBC_FUNCS filter, but stubbing them with `void()` collides
// with the libc declarations. Leave them out; the linker will resolve at load.

#endif  // __ANDROID__
