// Auto-generated by platform/android/scripts/regen_stubs.sh.
//
// Bionic's dlopen() rejects .so files with GLOBAL UND symbols not provided
// by an already-loaded shared library. We link with
// -Wl,--unresolved-symbols=ignore-all so the link succeeds despite leftover
// desktop-only references (SDL2, NFD, RecompFrontend recompui/recompinput,
// re-spirv, ImGui_SDL2). To make dlopen happy we provide a tiny per-symbol
// stub for every UND name that logs the offending symbol via logcat and
// aborts. The boot path in src/main/android_run_game.cpp deliberately
// avoids invoking these code paths; if one of them does fire, the logcat
// line tells us exactly which to implement next.
//
// EXCLUDES (don't stub these - system libraries provide them):
//   - Android NDK funcs matching ^A[A-Z][a-zA-Z]*_  (libandroid.so)
//   - __android_log_*  (liblog.so)
//   - vk*, volk*       (libvulkan.so + volk)
//   - pthread_*, sem_* (Bionic libc)
//   - libm / libdl     (Bionic)
//   - libc++_shared.so symbols (_ZNSt*, _ZNKSt*, _ZN6__ndk1*, etc.)
//   - libc++abi __cxa_*, _Unwind_*, __gxx_personality_*
//
// Regenerate after the link-error list changes:
//   platform/android/scripts/regen_stubs.sh

#ifdef __ANDROID__
#include <android/log.h>
#include <stdlib.h>

extern "C" __attribute__((noreturn)) void android_unimplemented_stub_named(const char* name) {
    __android_log_print(ANDROID_LOG_FATAL, "BK64-Stub",
        "unimplemented Android stub called: %s -- aborting", name);
    abort();
}

extern "C" void SDL_AddEventWatch() { android_unimplemented_stub_named("SDL_AddEventWatch"); }
extern "C" void SDL_BuildAudioCVT() { android_unimplemented_stub_named("SDL_BuildAudioCVT"); }
extern "C" void SDL_ConvertAudio() { android_unimplemented_stub_named("SDL_ConvertAudio"); }
extern "C" void SDL_CreateSystemCursor() { android_unimplemented_stub_named("SDL_CreateSystemCursor"); }
extern "C" void SDL_CreateWindow() { android_unimplemented_stub_named("SDL_CreateWindow"); }
extern "C" void SDL_DelEventWatch() { android_unimplemented_stub_named("SDL_DelEventWatch"); }
extern "C" void SDL_FreeCursor() { android_unimplemented_stub_named("SDL_FreeCursor"); }
extern "C" void SDL_GL_GetDrawableSize() { android_unimplemented_stub_named("SDL_GL_GetDrawableSize"); }
extern "C" void SDL_GameControllerAddMappingsFromRW() { android_unimplemented_stub_named("SDL_GameControllerAddMappingsFromRW"); }
extern "C" void SDL_GetClipboardText() { android_unimplemented_stub_named("SDL_GetClipboardText"); }
extern "C" void SDL_GetCurrentVideoDriver() { android_unimplemented_stub_named("SDL_GetCurrentVideoDriver"); }
extern "C" void SDL_GetError() { android_unimplemented_stub_named("SDL_GetError"); }
extern "C" void SDL_GetEventFilter() { android_unimplemented_stub_named("SDL_GetEventFilter"); }
extern "C" void SDL_GetGlobalMouseState() { android_unimplemented_stub_named("SDL_GetGlobalMouseState"); }
extern "C" void SDL_GetKeyboardFocus() { android_unimplemented_stub_named("SDL_GetKeyboardFocus"); }
extern "C" void SDL_GetMouseFocus() { android_unimplemented_stub_named("SDL_GetMouseFocus"); }
extern "C" void SDL_GetPerformanceCounter() { android_unimplemented_stub_named("SDL_GetPerformanceCounter"); }
extern "C" void SDL_GetPerformanceFrequency() { android_unimplemented_stub_named("SDL_GetPerformanceFrequency"); }
extern "C" void SDL_GetQueuedAudioSize() { android_unimplemented_stub_named("SDL_GetQueuedAudioSize"); }
extern "C" void SDL_GetRendererOutputSize() { android_unimplemented_stub_named("SDL_GetRendererOutputSize"); }
extern "C" void SDL_GetWindowFlags() { android_unimplemented_stub_named("SDL_GetWindowFlags"); }
extern "C" void SDL_GetWindowFromID() { android_unimplemented_stub_named("SDL_GetWindowFromID"); }
extern "C" void SDL_GetWindowPosition() { android_unimplemented_stub_named("SDL_GetWindowPosition"); }
extern "C" void SDL_GetWindowSize() { android_unimplemented_stub_named("SDL_GetWindowSize"); }
extern "C" void SDL_GetWindowWMInfo() { android_unimplemented_stub_named("SDL_GetWindowWMInfo"); }
extern "C" void SDL_Init() { android_unimplemented_stub_named("SDL_Init"); }
extern "C" void SDL_InitSubSystem() { android_unimplemented_stub_named("SDL_InitSubSystem"); }
extern "C" void SDL_OpenAudioDevice() { android_unimplemented_stub_named("SDL_OpenAudioDevice"); }
extern "C" void SDL_PauseAudioDevice() { android_unimplemented_stub_named("SDL_PauseAudioDevice"); }
extern "C" void SDL_QueueAudio() { android_unimplemented_stub_named("SDL_QueueAudio"); }
extern "C" void SDL_RWFromFile() { android_unimplemented_stub_named("SDL_RWFromFile"); }
extern "C" void SDL_SetClipboardText() { android_unimplemented_stub_named("SDL_SetClipboardText"); }
extern "C" void SDL_SetCursor() { android_unimplemented_stub_named("SDL_SetCursor"); }
extern "C" void SDL_SetEventFilter() { android_unimplemented_stub_named("SDL_SetEventFilter"); }
extern "C" void SDL_SetHint() { android_unimplemented_stub_named("SDL_SetHint"); }
extern "C" void SDL_SetTextInputRect() { android_unimplemented_stub_named("SDL_SetTextInputRect"); }
extern "C" void SDL_ShowCursor() { android_unimplemented_stub_named("SDL_ShowCursor"); }
extern "C" void SDL_StartTextInput() { android_unimplemented_stub_named("SDL_StartTextInput"); }
extern "C" void SDL_StopTextInput() { android_unimplemented_stub_named("SDL_StopTextInput"); }
extern "C" void SDL_WarpMouseInWindow() { android_unimplemented_stub_named("SDL_WarpMouseInWindow"); }
extern "C" void SDL_WasInit() { android_unimplemented_stub_named("SDL_WasInit"); }
extern "C" void SDL_free() { android_unimplemented_stub_named("SDL_free"); }
extern "C" void _ZN11recompinput11poll_inputsEv() { android_unimplemented_stub_named("_ZN11recompinput11poll_inputsEv"); }
extern "C" void _ZN8recompui10GameOption12set_callbackENSt6__ndk18functionIFvvEEE() { android_unimplemented_stub_named("_ZN8recompui10GameOption12set_callbackENSt6__ndk18functionIFvvEEE"); }
extern "C" void _ZN8recompui10IconButton20add_pressed_callbackENSt6__ndk18functionIFvvEEE() { android_unimplemented_stub_named("_ZN8recompui10IconButton20add_pressed_callbackENSt6__ndk18functionIFvvEEE"); }
extern "C" void _ZN8recompui10IconButtonC1ENS_10ResourceIdEPNS_7ElementERKNSt6__ndk112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEENS_11ButtonStyleENS_14IconButtonSizeE() { android_unimplemented_stub_named("_ZN8recompui10IconButtonC1ENS_10ResourceIdEPNS_7ElementERKNSt6__ndk112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEENS_11ButtonStyleENS_14IconButtonSizeE"); }
extern "C" void _ZN8recompui11message_boxEPKc() { android_unimplemented_stub_named("_ZN8recompui11message_boxEPKc"); }
extern "C" void _ZN8recompui12LauncherMenu20remove_default_titleEv() { android_unimplemented_stub_named("_ZN8recompui12LauncherMenu20remove_default_titleEv"); }
extern "C" void _ZN8recompui12LauncherMenu22init_game_options_menuENSt6__ndk112basic_stringIDuNS1_11char_traitsIDuEENS1_9allocatorIDuEEEENS2_IcNS3_IcEENS5_IcEEEESA_NS1_4spanIKcLm18446744073709551615EEENS_21GameOptionsMenuLayoutE() { android_unimplemented_stub_named("_ZN8recompui12LauncherMenu22init_game_options_menuENSt6__ndk112basic_stringIDuNS1_11char_traitsIDuEENS1_9allocatorIDuEEEENS2_IcNS3_IcEENS5_IcEEEESA_NS1_4spanIKcLm18446744073709551615EEENS_21GameOptionsMenuLayoutE"); }
extern "C" void _ZN8recompui12hide_contextENS_9ContextIdE() { android_unimplemented_stub_named("_ZN8recompui12hide_contextENS_9ContextIdE"); }
extern "C" void _ZN8recompui12show_contextENS_9ContextIdENSt6__ndk117basic_string_viewIcNS1_11char_traitsIcEEEE() { android_unimplemented_stub_named("_ZN8recompui12show_contextENS_9ContextIdENSt6__ndk117basic_string_viewIcNS1_11char_traitsIcEEEE"); }
extern "C" void _ZN8recompui13programconfig14set_program_idERKNSt6__ndk112basic_stringIDuNS1_11char_traitsIDuEENS1_9allocatorIDuEEEE() { android_unimplemented_stub_named("_ZN8recompui13programconfig14set_program_idERKNSt6__ndk112basic_stringIDuNS1_11char_traitsIDuEENS1_9allocatorIDuEEEE"); }
extern "C" void _ZN8recompui13programconfig16set_program_nameERKNSt6__ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE() { android_unimplemented_stub_named("_ZN8recompui13programconfig16set_program_nameERKNSt6__ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE"); }
extern "C" void _ZN8recompui14create_contextEv() { android_unimplemented_stub_named("_ZN8recompui14create_contextEv"); }
extern "C" void _ZN8recompui15GameOptionsMenu10add_optionERKNSt6__ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS1_8functionIFvvEEE() { android_unimplemented_stub_named("_ZN8recompui15GameOptionsMenu10add_optionERKNSt6__ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS1_8functionIFvvEEE"); }
extern "C" void _ZN8recompui15GameOptionsMenu15add_exit_optionERKNSt6__ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE() { android_unimplemented_stub_named("_ZN8recompui15GameOptionsMenu15add_exit_optionERKNSt6__ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE"); }
extern "C" void _ZN8recompui15GameOptionsMenu19add_settings_optionERKNSt6__ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE() { android_unimplemented_stub_named("_ZN8recompui15GameOptionsMenu19add_settings_optionERKNSt6__ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE"); }
extern "C" void _ZN8recompui15GameOptionsMenu33add_start_game_or_load_rom_optionERKNSt6__ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES9_() { android_unimplemented_stub_named("_ZN8recompui15GameOptionsMenu33add_start_game_or_load_rom_optionERKNSt6__ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES9_"); }
extern "C" void _ZN8recompui16is_context_shownENS_9ContextIdE() { android_unimplemented_stub_named("_ZN8recompui16is_context_shownENS_9ContextIdE"); }
extern "C" void _ZN8recompui16open_info_promptERKNSt6__ndk112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEES8_S8_NS0_8functionIFvvEEENS_11ButtonStyleE() { android_unimplemented_stub_named("_ZN8recompui16open_info_promptERKNSt6__ndk112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEES8_S8_NS0_8functionIFvvEEENS_11ButtonStyleE"); }
extern "C" void _ZN8recompui17hide_all_contextsEv() { android_unimplemented_stub_named("_ZN8recompui17hide_all_contextsEv"); }
extern "C" void _ZN8recompui18open_choice_promptERKNSt6__ndk112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEES8_S8_S8_NS0_8functionIFvvEEESB_NS_11ButtonStyleESC_b() { android_unimplemented_stub_named("_ZN8recompui18open_choice_promptERKNSt6__ndk112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEES8_S8_S8_NS0_8functionIFvvEEESB_NS_11ButtonStyleESC_b"); }
extern "C" void _ZN8recompui18set_online_sessionEb() { android_unimplemented_stub_named("_ZN8recompui18set_online_sessionEb"); }
extern "C" void _ZN8recompui18set_translation_fnENSt6__ndk18functionIFNS0_12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEENS0_17basic_string_viewIcS4_EES9_EEE() { android_unimplemented_stub_named("_ZN8recompui18set_translation_fnENSt6__ndk18functionIFNS0_12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEENS0_17basic_string_viewIcS4_EES9_EEE"); }
extern "C" void _ZN8recompui18update_game_mod_idERKNSt6__ndk112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE() { android_unimplemented_stub_named("_ZN8recompui18update_game_mod_idERKNSt6__ndk112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE"); }
extern "C" void _ZN8recompui19get_current_contextEv() { android_unimplemented_stub_named("_ZN8recompui19get_current_contextEv"); }
extern "C" void _ZN8recompui19register_extra_fontERKNSt6__ndk112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE() { android_unimplemented_stub_named("_ZN8recompui19register_extra_fontERKNSt6__ndk112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE"); }
extern "C" void _ZN8recompui19register_ui_exportsEv() { android_unimplemented_stub_named("_ZN8recompui19register_ui_exportsEv"); }
extern "C" void _ZN8recompui21register_primary_fontERKNSt6__ndk112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEES8_() { android_unimplemented_stub_named("_ZN8recompui21register_primary_fontERKNSt6__ndk112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEES8_"); }
extern "C" void _ZN8recompui23get_launcher_context_idEv() { android_unimplemented_stub_named("_ZN8recompui23get_launcher_context_idEv"); }
extern "C" void _ZN8recompui29set_quit_to_launcher_callbackENSt6__ndk18functionIFvvEEE() { android_unimplemented_stub_named("_ZN8recompui29set_quit_to_launcher_callbackENSt6__ndk18functionIFvvEEE"); }
extern "C" void _ZN8recompui31register_launcher_init_callbackENSt6__ndk18functionIFvPNS_12LauncherMenuEEEE() { android_unimplemented_stub_named("_ZN8recompui31register_launcher_init_callbackENSt6__ndk18functionIFvPNS_12LauncherMenuEEEE"); }
extern "C" void _ZN8recompui33register_launcher_update_callbackENSt6__ndk18functionIFvPNS_12LauncherMenuEEEE() { android_unimplemented_stub_named("_ZN8recompui33register_launcher_update_callbackENSt6__ndk18functionIFvPNS_12LauncherMenuEEEE"); }
extern "C" void _ZN8recompui3SvgC1ENS_10ResourceIdEPNS_7ElementENSt6__ndk117basic_string_viewIcNS4_11char_traitsIcEEEE() { android_unimplemented_stub_named("_ZN8recompui3SvgC1ENS_10ResourceIdEPNS_7ElementENSt6__ndk117basic_string_viewIcNS4_11char_traitsIcEEEE"); }
extern "C" void _ZN8recompui4file16get_program_pathEv() { android_unimplemented_stub_named("_ZN8recompui4file16get_program_pathEv"); }
extern "C" void _ZN8recompui4file19get_app_folder_pathEv() { android_unimplemented_stub_named("_ZN8recompui4file19get_app_folder_pathEv"); }
extern "C" void _ZN8recompui5LabelC1ENS_10ResourceIdEPNS_7ElementERKNSt6__ndk112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEENS_10LabelStyleE() { android_unimplemented_stub_named("_ZN8recompui5LabelC1ENS_10ResourceIdEPNS_7ElementERKNSt6__ndk112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEENS_10LabelStyleE"); }
extern "C" void _ZN8recompui5LabelC1ENS_10ResourceIdEPNS_7ElementERKNSt6__ndk112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEENS_5theme10TypographyE() { android_unimplemented_stub_named("_ZN8recompui5LabelC1ENS_10ResourceIdEPNS_7ElementERKNSt6__ndk112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEENS_5theme10TypographyE"); }
extern "C" void _ZN8recompui5Style10set_bottomEfNS_4UnitE() { android_unimplemented_stub_named("_ZN8recompui5Style10set_bottomEfNS_4UnitE"); }
extern "C" void _ZN8recompui5Style10set_heightEfNS_4UnitE() { android_unimplemented_stub_named("_ZN8recompui5Style10set_heightEfNS_4UnitE"); }
extern "C" void _ZN8recompui5Style10unset_leftEv() { android_unimplemented_stub_named("_ZN8recompui5Style10unset_leftEv"); }
extern "C" void _ZN8recompui5Style11set_displayENS_7DisplayE() { android_unimplemented_stub_named("_ZN8recompui5Style11set_displayENS_7DisplayE"); }
extern "C" void _ZN8recompui5Style11set_opacityEf() { android_unimplemented_stub_named("_ZN8recompui5Style11set_opacityEf"); }
extern "C" void _ZN8recompui5Style11set_paddingEfNS_4UnitE() { android_unimplemented_stub_named("_ZN8recompui5Style11set_paddingEfNS_4UnitE"); }
extern "C" void _ZN8recompui5Style12display_hideEv() { android_unimplemented_stub_named("_ZN8recompui5Style12display_hideEv"); }
extern "C" void _ZN8recompui5Style12display_showEv() { android_unimplemented_stub_named("_ZN8recompui5Style12display_showEv"); }
extern "C" void _ZN8recompui5Style12set_overflowENS_8OverflowE() { android_unimplemented_stub_named("_ZN8recompui5Style12set_overflowENS_8OverflowE"); }
extern "C" void _ZN8recompui5Style12set_positionENS_8PositionE() { android_unimplemented_stub_named("_ZN8recompui5Style12set_positionENS_8PositionE"); }
extern "C" void _ZN8recompui5Style12set_rotationEf() { android_unimplemented_stub_named("_ZN8recompui5Style12set_rotationEf"); }
extern "C" void _ZN8recompui5Style12set_scale_2DEff() { android_unimplemented_stub_named("_ZN8recompui5Style12set_scale_2DEff"); }
extern "C" void _ZN8recompui5Style13set_flex_growEf() { android_unimplemented_stub_named("_ZN8recompui5Style13set_flex_growEf"); }
extern "C" void _ZN8recompui5Style13set_font_sizeEfNS_4UnitE() { android_unimplemented_stub_named("_ZN8recompui5Style13set_font_sizeEfNS_4UnitE"); }
extern "C" void _ZN8recompui5Style13set_max_widthEfNS_4UnitE() { android_unimplemented_stub_named("_ZN8recompui5Style13set_max_widthEfNS_4UnitE"); }
extern "C" void _ZN8recompui5Style13set_min_widthEfNS_4UnitE() { android_unimplemented_stub_named("_ZN8recompui5Style13set_min_widthEfNS_4UnitE"); }
extern "C" void _ZN8recompui5Style14set_margin_topEfNS_4UnitE() { android_unimplemented_stub_named("_ZN8recompui5Style14set_margin_topEfNS_4UnitE"); }
extern "C" void _ZN8recompui5Style14set_max_heightEfNS_4UnitE() { android_unimplemented_stub_named("_ZN8recompui5Style14set_max_heightEfNS_4UnitE"); }
extern "C" void _ZN8recompui5Style14set_min_heightEfNS_4UnitE() { android_unimplemented_stub_named("_ZN8recompui5Style14set_min_heightEfNS_4UnitE"); }
extern "C" void _ZN8recompui5Style14set_overflow_yENS_8OverflowE() { android_unimplemented_stub_named("_ZN8recompui5Style14set_overflow_yENS_8OverflowE"); }
extern "C" void _ZN8recompui5Style14set_text_alignENS_9TextAlignE() { android_unimplemented_stub_named("_ZN8recompui5Style14set_text_alignENS_9TextAlignE"); }
extern "C" void _ZN8recompui5Style15set_align_itemsENS_10AlignItemsE() { android_unimplemented_stub_named("_ZN8recompui5Style15set_align_itemsENS_10AlignItemsE"); }
extern "C" void _ZN8recompui5Style15set_font_weightEj() { android_unimplemented_stub_named("_ZN8recompui5Style15set_font_weightEj"); }
extern "C" void _ZN8recompui5Style15set_margin_leftEfNS_4UnitE() { android_unimplemented_stub_named("_ZN8recompui5Style15set_margin_leftEfNS_4UnitE"); }
extern "C" void _ZN8recompui5Style15set_padding_topEfNS_4UnitE() { android_unimplemented_stub_named("_ZN8recompui5Style15set_padding_topEfNS_4UnitE"); }
extern "C" void _ZN8recompui5Style16set_border_colorENS_5theme5colorEi() { android_unimplemented_stub_named("_ZN8recompui5Style16set_border_colorENS_5theme5colorEi"); }
extern "C" void _ZN8recompui5Style16set_border_widthEfNS_4UnitE() { android_unimplemented_stub_named("_ZN8recompui5Style16set_border_widthEfNS_4UnitE"); }
extern "C" void _ZN8recompui5Style16set_margin_rightEfNS_4UnitE() { android_unimplemented_stub_named("_ZN8recompui5Style16set_margin_rightEfNS_4UnitE"); }
extern "C" void _ZN8recompui5Style16set_padding_leftEfNS_4UnitE() { android_unimplemented_stub_named("_ZN8recompui5Style16set_padding_leftEfNS_4UnitE"); }
extern "C" void _ZN8recompui5Style16set_translate_2DEffNS_4UnitE() { android_unimplemented_stub_named("_ZN8recompui5Style16set_translate_2DEffNS_4UnitE"); }
extern "C" void _ZN8recompui5Style17set_border_radiusEfNS_4UnitE() { android_unimplemented_stub_named("_ZN8recompui5Style17set_border_radiusEfNS_4UnitE"); }
extern "C" void _ZN8recompui5Style17set_margin_bottomEfNS_4UnitE() { android_unimplemented_stub_named("_ZN8recompui5Style17set_margin_bottomEfNS_4UnitE"); }
extern "C" void _ZN8recompui5Style17set_padding_rightEfNS_4UnitE() { android_unimplemented_stub_named("_ZN8recompui5Style17set_padding_rightEfNS_4UnitE"); }
extern "C" void _ZN8recompui5Style18set_flex_directionENS_13FlexDirectionE() { android_unimplemented_stub_named("_ZN8recompui5Style18set_flex_directionENS_13FlexDirectionE"); }
extern "C" void _ZN8recompui5Style18set_letter_spacingEfNS_4UnitE() { android_unimplemented_stub_named("_ZN8recompui5Style18set_letter_spacingEfNS_4UnitE"); }
extern "C" void _ZN8recompui5Style18set_padding_bottomEfNS_4UnitE() { android_unimplemented_stub_named("_ZN8recompui5Style18set_padding_bottomEfNS_4UnitE"); }
extern "C" void _ZN8recompui5Style19set_justify_contentENS_14JustifyContentE() { android_unimplemented_stub_named("_ZN8recompui5Style19set_justify_contentENS_14JustifyContentE"); }
extern "C" void _ZN8recompui5Style20set_background_colorENS_5theme5colorEi() { android_unimplemented_stub_named("_ZN8recompui5Style20set_background_colorENS_5theme5colorEi"); }
extern "C" void _ZN8recompui5Style20set_background_colorERKNS_5ColorE() { android_unimplemented_stub_named("_ZN8recompui5Style20set_background_colorERKNS_5ColorE"); }
extern "C" void _ZN8recompui5Style7set_gapEfNS_4UnitE() { android_unimplemented_stub_named("_ZN8recompui5Style7set_gapEfNS_4UnitE"); }
extern "C" void _ZN8recompui5Style7set_topEfNS_4UnitE() { android_unimplemented_stub_named("_ZN8recompui5Style7set_topEfNS_4UnitE"); }
extern "C" void _ZN8recompui5Style8set_leftEfNS_4UnitE() { android_unimplemented_stub_named("_ZN8recompui5Style8set_leftEfNS_4UnitE"); }
extern "C" void _ZN8recompui5Style9set_colorENS_5theme5colorEi() { android_unimplemented_stub_named("_ZN8recompui5Style9set_colorENS_5theme5colorEi"); }
extern "C" void _ZN8recompui5Style9set_colorERKNS_5ColorE() { android_unimplemented_stub_named("_ZN8recompui5Style9set_colorERKNS_5ColorE"); }
extern "C" void _ZN8recompui5Style9set_rightEfNS_4UnitE() { android_unimplemented_stub_named("_ZN8recompui5Style9set_rightEfNS_4UnitE"); }
extern "C" void _ZN8recompui5Style9set_widthEfNS_4UnitE() { android_unimplemented_stub_named("_ZN8recompui5Style9set_widthEfNS_4UnitE"); }
extern "C" void _ZN8recompui5theme15set_theme_colorENS0_5colorERKNS_5ColorE() { android_unimplemented_stub_named("_ZN8recompui5theme15set_theme_colorENS0_5colorERKNS_5ColorE"); }
extern "C" void _ZN8recompui5theme21set_typography_presetENS0_10TypographyEffjNS_9FontStyleE() { android_unimplemented_stub_named("_ZN8recompui5theme21set_typography_presetENS0_10TypographyEffjNS_9FontStyleE"); }
extern "C" void _ZN8recompui5theme6border9radius_lgE() { android_unimplemented_stub_named("_ZN8recompui5theme6border9radius_lgE"); }
extern "C" void _ZN8recompui5theme6border9radius_mdE() { android_unimplemented_stub_named("_ZN8recompui5theme6border9radius_mdE"); }
extern "C" void _ZN8recompui5theme6border9radius_smE() { android_unimplemented_stub_named("_ZN8recompui5theme6border9radius_smE"); }
extern "C" void _ZN8recompui6Button18apply_button_styleENS_11ButtonStyleE() { android_unimplemented_stub_named("_ZN8recompui6Button18apply_button_styleENS_11ButtonStyleE"); }
extern "C" void _ZN8recompui6Button20add_pressed_callbackENSt6__ndk18functionIFvvEEE() { android_unimplemented_stub_named("_ZN8recompui6Button20add_pressed_callbackENSt6__ndk18functionIFvvEEE"); }
extern "C" void _ZN8recompui6ButtonC1ENS_10ResourceIdEPNS_7ElementERKNSt6__ndk112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEENS_11ButtonStyleENS_10ButtonSizeE() { android_unimplemented_stub_named("_ZN8recompui6ButtonC1ENS_10ResourceIdEPNS_7ElementERKNSt6__ndk112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEENS_11ButtonStyleENS_10ButtonSizeE"); }
extern "C" void _ZN8recompui6config15create_mods_tabERKNSt6__ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE() { android_unimplemented_stub_named("_ZN8recompui6config15create_mods_tabERKNSt6__ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE"); }
extern "C" void _ZN8recompui6config16create_sound_tabERKNSt6__ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE() { android_unimplemented_stub_named("_ZN8recompui6config16create_sound_tabERKNSt6__ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE"); }
extern "C" void _ZN8recompui6config16get_sound_configEv() { android_unimplemented_stub_named("_ZN8recompui6config16get_sound_configEv"); }
extern "C" void _ZN8recompui6config18create_general_tabERKNS0_17GeneralTabOptionsERKNSt6__ndk112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEE() { android_unimplemented_stub_named("_ZN8recompui6config18create_general_tabERKNS0_17GeneralTabOptionsERKNSt6__ndk112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEE"); }
extern "C" void _ZN8recompui6config18get_general_configEv() { android_unimplemented_stub_named("_ZN8recompui6config18get_general_configEv"); }
extern "C" void _ZN8recompui6config19create_controls_tabERKNSt6__ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE() { android_unimplemented_stub_named("_ZN8recompui6config19create_controls_tabERKNSt6__ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE"); }
extern "C" void _ZN8recompui6config19create_graphics_tabERKNSt6__ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE() { android_unimplemented_stub_named("_ZN8recompui6config19create_graphics_tabERKNSt6__ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE"); }
extern "C" void _ZN8recompui6config19get_graphics_configEv() { android_unimplemented_stub_named("_ZN8recompui6config19get_graphics_configEv"); }
extern "C" void _ZN8recompui6config5sound15get_main_volumeEv() { android_unimplemented_stub_named("_ZN8recompui6config5sound15get_main_volumeEv"); }
extern "C" void _ZN8recompui6config8finalizeEv() { android_unimplemented_stub_named("_ZN8recompui6config8finalizeEv"); }
extern "C" void _ZN8recompui7Element11set_enabledEb() { android_unimplemented_stub_named("_ZN8recompui7Element11set_enabledEb"); }
extern "C" void _ZN8recompui7Element14clear_childrenEv() { android_unimplemented_stub_named("_ZN8recompui7Element14clear_childrenEv"); }
extern "C" void _ZN8recompui7Element16get_client_widthEv() { android_unimplemented_stub_named("_ZN8recompui7Element16get_client_widthEv"); }
extern "C" void _ZN8recompui7Element17get_client_heightEv() { android_unimplemented_stub_named("_ZN8recompui7Element17get_client_heightEv"); }
extern "C" void _ZN8recompui7Element21get_dp_to_pixel_ratioEv() { android_unimplemented_stub_named("_ZN8recompui7Element21get_dp_to_pixel_ratioEv"); }
extern "C" void _ZN8recompui7Element27set_as_navigation_containerENS_14NavigationTypeE() { android_unimplemented_stub_named("_ZN8recompui7Element27set_as_navigation_containerENS_14NavigationTypeE"); }
extern "C" void _ZN8recompui7ElementC1ENS_10ResourceIdEPS0_jNSt6__ndk112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEb() { android_unimplemented_stub_named("_ZN8recompui7ElementC1ENS_10ResourceIdEPS0_jNSt6__ndk112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEb"); }
extern "C" void _ZN8recompui8renderer19enable_texture_packERKN6recomp4mods10ModContextERKNS2_9ModHandleE() { android_unimplemented_stub_named("_ZN8recompui8renderer19enable_texture_packERKN6recomp4mods10ModContextERKNS2_9ModHandleE"); }
extern "C" void _ZN8recompui8renderer20disable_texture_packERKN6recomp4mods9ModHandleE() { android_unimplemented_stub_named("_ZN8recompui8renderer20disable_texture_packERKN6recomp4mods9ModHandleE"); }
extern "C" void _ZN8recompui8renderer21create_render_contextEPhP13ANativeWindowN11ultramodern8renderer16PresentationModeEb() { android_unimplemented_stub_named("_ZN8recompui8renderer21create_render_contextEPhP13ANativeWindowN11ultramodern8renderer16PresentationModeEb"); }
extern "C" void _ZN8recompui8renderer26RT64HighPrecisionFBEnabledEv() { android_unimplemented_stub_named("_ZN8recompui8renderer26RT64HighPrecisionFBEnabledEv"); }
extern "C" void _ZN8recompui8renderer27trigger_texture_pack_updateEv() { android_unimplemented_stub_named("_ZN8recompui8renderer27trigger_texture_pack_updateEv"); }
extern "C" void _ZN8recompui9Clickable20add_clicked_callbackENSt6__ndk18functionIFvffEEE() { android_unimplemented_stub_named("_ZN8recompui9Clickable20add_clicked_callbackENSt6__ndk18functionIFvffEEE"); }
extern "C" void _ZN8recompui9ClickableC1ENS_10ResourceIdEPNS_7ElementEb() { android_unimplemented_stub_named("_ZN8recompui9ClickableC1ENS_10ResourceIdEPNS_7ElementEb"); }
extern "C" void _ZN8recompui9ContextId16get_root_elementEv() { android_unimplemented_stub_named("_ZN8recompui9ContextId16get_root_elementEv"); }
extern "C" void _ZN8recompui9ContextId17add_resource_implENS_10ResourceIdEONSt6__ndk110unique_ptrINS_5StyleENS2_14default_deleteIS4_EEEE() { android_unimplemented_stub_named("_ZN8recompui9ContextId17add_resource_implENS_10ResourceIdEONSt6__ndk110unique_ptrINS_5StyleENS2_14default_deleteIS4_EEEE"); }
extern "C" void _ZN8recompui9ContextId18set_captures_inputEb() { android_unimplemented_stub_named("_ZN8recompui9ContextId18set_captures_inputEb"); }
extern "C" void _ZN8recompui9ContextId18set_captures_mouseEb() { android_unimplemented_stub_named("_ZN8recompui9ContextId18set_captures_mouseEb"); }
extern "C" void _ZN8recompui9ContextId20create_resource_implEb() { android_unimplemented_stub_named("_ZN8recompui9ContextId20create_resource_implEb"); }
extern "C" void _ZN8recompui9ContextId4openEv() { android_unimplemented_stub_named("_ZN8recompui9ContextId4openEv"); }
extern "C" void _ZN8recompui9ContextId5closeEv() { android_unimplemented_stub_named("_ZN8recompui9ContextId5closeEv"); }
extern "C" void _ZN8recompui9TextInput8get_textEv() { android_unimplemented_stub_named("_ZN8recompui9TextInput8get_textEv"); }
extern "C" void _ZN8recompui9TextInputC1ENS_10ResourceIdEPNS_7ElementEb() { android_unimplemented_stub_named("_ZN8recompui9TextInputC1ENS_10ResourceIdEPNS_7ElementEb"); }

#endif  // __ANDROID__
