#include "embedded_mods.h"

#include "librecomp/mods.hpp"

#include <cstdint>
#include <span>
#include <string>
#include <unordered_map>
#include <vector>

// Generated by file_to_c via the CMake glob over BanjoRecomp/embedded_mods/*.{nrm,rtz}.
// Each header declares `extern const char <name>[N]` and `extern const size_t <name>_size`,
// where <name> is the filename (without extension). The headers already wrap themselves
// in `extern "C"` for C++ consumers, so no extra wrapper is needed here.
#include "embedded_mods/bk_spanish_translation.h"
#include "embedded_mods/bk_locale_french.h"
#include "embedded_mods/german.h"
#include "embedded_mods/banjo_ptbr.h"
#include "embedded_mods/banjo_ptbr_fontes.h"          // .rtz texture pack (PT-BR)
#include "embedded_mods/spanish_hd_fonts.h"           // .rtz texture pack (Spanish accents)
#include "embedded_mods/bk_recomp_asset_expansion_pak.h"
#include "embedded_mods/font_plus_latin_1.h"

namespace {

struct EmbeddedMod {
    std::string mod_id;          // canonical id from the mod's manifest (or filename for manifest-less .rtz)
    const char* bytes;           // pointer to the C array (signed char)
    size_t       size;
    std::string  container_ext;  // ".nrm" for code mods, ".rtz" for texture packs
};

// Map filename-based arrays to the mod_id that ships inside each container.
// Filename and mod_id can differ (e.g. `german.nrm` -> `de_v10lator_ger`); the
// generated array name follows the filename, the registered id follows the manifest.
const std::vector<EmbeddedMod>& bundled_mod_list() {
    static const std::vector<EmbeddedMod> v = {
        // --- Translation code mods (.nrm) ---
        { "bk_spanish_translation",        bk_spanish_translation,         bk_spanish_translation_size,        ".nrm" },
        { "lucaspec72_french_loc",         bk_locale_french,               bk_locale_french_size,              ".nrm" },
        { "de_v10lator_ger",               german,                         german_size,                        ".nrm" },
        { "bk_ptbr",                       banjo_ptbr,                     banjo_ptbr_size,                    ".nrm" },
        // --- Texture packs (.rtz) ---
        // bk_ptbr_fontes is a hard dep of the PT-BR mod (HD UI text textures).
        // bk_spanish_hd_fonts is the optional accented-glyph atlas for Spanish.
        { "bk_ptbr_fontes",                banjo_ptbr_fontes,              banjo_ptbr_fontes_size,             ".rtz" },
        { "bk_spanish_hd_fonts",           spanish_hd_fonts,               spanish_hd_fonts_size,              ".rtz" },
        // --- Shared dependencies ---
        { "bk_recomp_asset_expansion_pak", bk_recomp_asset_expansion_pak,  bk_recomp_asset_expansion_pak_size, ".nrm" },
        { "font_plus_latin_1",             font_plus_latin_1,              font_plus_latin_1_size,             ".nrm" },
    };
    return v;
}

// Returns the set of mod ids that should be enabled for the given launcher locale,
// and the set that should be disabled (so a previous language's pack doesn't stay on
// in the user's mods.json after they switch).
std::unordered_map<std::string, bool> overrides_for_language(banjo::Language lang) {
    using L = banjo::Language;

    // Default: every embedded mod off.
    std::unordered_map<std::string, bool> out;
    for (const auto& m : bundled_mod_list()) out[m.mod_id] = false;

    auto enable = [&](const char* id) { out[id] = true; };

    switch (lang) {
        case L::Spanish:
            // bk_spanish_hd_fonts (.rtz) is the optional but recommended HD glyph
            // atlas with accented Latin chars (a/e/i/o/u-acute, n-tilde) that the
            // base font lacks. Without it Spanish text shows but loses its accents.
            enable("bk_spanish_translation");
            enable("bk_recomp_asset_expansion_pak");
            enable("bk_spanish_hd_fonts");
            break;
        case L::French:
            // NOTE: do NOT enable bk_recomp_asset_expansion_pak — both mods patch
            // the same asset function and the French mod refuses to load with
            // "Conflicts with other mod: bk_recomp_asset_expansion_pak".
            //
            // Also do NOT enable font_plus_latin_1 — it remaps the glyph atlas in
            // a way the French mod doesn't expect, producing empty boxes for every
            // character. The mod ships `deAccentifier.ps1` and its strings are
            // already de-accented to ASCII (`francais`, `deconnecte`), so the base
            // game font renders them fine without Latin-1 support.
            enable("lucaspec72_french_loc");
            break;
        case L::German:
            // NOTE: do NOT enable font_plus_latin_1 here. The German mod
            // detects the Latin-1 font replacement at runtime and self-disables
            // ("Font Plus Latin 1 mod detected! Disabling german...") — its
            // own description states "Conflicts: This mod conflicts with the
            // Latin 1 mod". The optional_dependencies entry in its manifest
            // is for load-order, not for runtime coexistence.
            enable("de_v10lator_ger");
            enable("bk_recomp_asset_expansion_pak");
            break;
        case L::Portuguese:
            // PT-BR mod's hard dep is `bk_ptbr_fontes` which IS the bundled
            // .rtz texture pack (HD textures for translated UI elements).
            enable("bk_ptbr");
            enable("bk_ptbr_fontes");
            break;
        case L::English:
        default:
            // No translation pack — keep everything off.
            break;
    }
    return out;
}

} // anonymous

namespace banjo::embedded_mods {

void initialize(banjo::Language launcher_language) {
    // Register the raw bytes — librecomp will open them in scan_mod_folder().
    // open_mod_from_memory expects span<const uint8_t>; the file_to_c arrays are
    // declared as `const char[]` so we reinterpret here.
    for (const auto& m : bundled_mod_list()) {
        std::span<const uint8_t> bytes{
            reinterpret_cast<const uint8_t*>(m.bytes),
            m.size
        };
        recomp::mods::register_embedded_mod(m.mod_id, bytes, m.container_ext);
    }

    // Drive enable/disable from the launcher locale. This wins over the user's
    // mods.json so switching language Just Works (after a restart, which the
    // language picker already prompts for).
    recomp::mods::set_force_enabled_overrides(overrides_for_language(launcher_language));

    printf("[embedded_mods] Registered %zu bundled mods, locale=%d\n",
           bundled_mod_list().size(), static_cast<int>(launcher_language));
}

} // namespace banjo::embedded_mods
